services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pagevault_db'
      - 'POSTGRES_PASSWORD=pagevault_user'
      - 'POSTGRES_USER=pagevault_user'
      - 'POSTGRES_PASSWORD: strong_password'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data:
